### ISSUE TITLE
 Feature Request: Support for Streaming Responses from OpenAI API

### ISSUE THREAD

**Issue by tranhoangnguyen03** [vendi-ai/declarai#107]
Being able to receive the output as a stream would be very helpful. Streaming would allow us to handle each chunk of data as it arrives, rather than waiting for the entire data set to be processed and sent back. This is particularly useful for dealing with GPT4 which has a rather long wait time to get a full completion answer without streaming.

Suggested format
```
@declarai.task(streaming=True)
def generate_large_text(title: str) -> AsyncIterator[str]:
    """
    Generate a large text based on the provided title, received in chunks.
    """

for chunk in generate_large_text(title="Some long text"):
    process_chunk(chunk)
```

**Comment by matankley** [comment]
Hey! thanks for raising that @tranhoangnguyen03 

I thought about the following:

![image](https://github.com/vendi-ai/declarai/assets/69151308/187dd1eb-6d57-4afa-9849-aff46171acc9)


Basically every chunk is the response of the given chunk .

What do you think about it ? Would that be convenient ?

**Comment by tranhoangnguyen03** [comment]
Looks really neat!

**Comment by matankley** [comment]
Merged. will be integrated in v0.1.9 later on this week.

**Comment by matankley** [comment]
@tranhoangnguyen03 Hey, we integrated steaming both to tasks and chats in v0.10.0. Please let me know if there anything else needed!

Thanks for your involvement and active part in declarai's journey!

Docs - https://declarai.com/features/streaming/
